name: run-rz-bindgen
on:
  push:
    paths:
    - 'src/**.py'
    - 'src/**.pyi'
    - 'src/**.i'
    - 'meson.build'
    - 'meson_options.txt'
  workflow_dispatch:

jobs:
  run-bindgen:
    uses: ./.github/workflows/bindgen.yml
    with:
      ref: dev

  publish-pypi:
    name: Publish PyPi
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [run-bindgen]
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist
    - name: Publish wheels
      uses: pypa/gh-action-pypi-publish@v1.5.1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
